package com.github.gquintana.beepbeep.sql;

import com.github.gquintana.beepbeep.pipeline.*;

import java.util.regex.Pattern;

public class SqlPipelineBuilder extends PipelineBuilder<SqlPipelineBuilder> {
    private SqlConnectionProvider connectionProvider;
    private boolean autoCommit = true;
    private String endOfLineRegex = ";\\s*$";

    public SqlPipelineBuilder withConnectionProvider(SqlConnectionProvider connectionProvider) {
        this.connectionProvider = connectionProvider;
        return self();
    }

    public SqlPipelineBuilder withConnectionProvider(String driverClass, String url, String username, String password) {
        return withConnectionProvider(new DriverSqlConnectionProvider(driverClass, url, username, password));
    }

    public SqlPipelineBuilder withAutoCommit(boolean autoCommit) {
        this.autoCommit = autoCommit;
        return self();
    }

    public SqlPipelineBuilder withManualCommit() {
        return withAutoCommit(false);
    }

    public SqlPipelineBuilder withEndOfLineRegex(String regex) {
        this.endOfLineRegex = regex;
        return self();
    }

    public SqlPipelineBuilder withEndOfLineMarker(String marker) {
        return withEndOfLineRegex(Pattern.quote(marker) + "\\s*$");
    }

    /**
     * Store ran script in table
     * @param name Table name
     * @param sequence True if ids are generated by sequence, false if they are generated by auto increment
     */
    public SqlPipelineBuilder withScriptStore(String name, boolean sequence) {
        return withScriptStore(new SqlScriptStore(getConnectionProvider(), name, sequence));
    }

    /**
     * Store ran script in table, don't use sequence to generate ids
     * @param name Table name
     */
    @Override
    public SqlPipelineBuilder withScriptStore(String name) {
        return withScriptStore(name, false);
    }

    @Override
    public  Consumer<ScriptStartEvent> createConsumers() {
        Consumer<ScriptEvent> consumer = endConsumer;
        consumer = new SqlLineExecutor(getConnectionProvider(), autoCommit, consumer);
        consumer = notNullNorEmptyFilter(consumer);
        consumer = new MultilineAggregator(endOfLineRegex, MultilineAggregator.LineMarkerStrategy.END, true, consumer);
        consumer = variableReplacer(consumer);
        return scriptReader(consumer);
    }

    protected SqlConnectionProvider getConnectionProvider() {
        return connectionProvider == null ?
            DriverSqlConnectionProvider.create(url, username, password) :
            connectionProvider;
    }
}
