package com.github.gquintana.beepbeep.sql;

import com.github.gquintana.beepbeep.pipeline.Consumer;
import com.github.gquintana.beepbeep.pipeline.MultilineAggregator;
import com.github.gquintana.beepbeep.pipeline.PipelineBuilder;
import com.github.gquintana.beepbeep.pipeline.ScriptEvent;
import com.github.gquintana.beepbeep.pipeline.ScriptStartEvent;
import com.github.gquintana.beepbeep.script.ScriptStores;
import com.github.gquintana.beepbeep.store.ScriptStore;

import java.util.regex.Pattern;

public class SqlPipelineBuilder extends PipelineBuilder<SqlPipelineBuilder> {
    private SqlConnectionProvider connectionProvider;
    private boolean autoCommit = true;
    private String endOfLineRegex = ";\\s*$";

    public SqlPipelineBuilder withConnectionProvider(SqlConnectionProvider connectionProvider) {
        this.connectionProvider = connectionProvider;
        return self();
    }

    public SqlPipelineBuilder withConnectionProvider(String driverClass, String url, String username, String password) {
        return withConnectionProvider(createConnectionProvider(driverClass, url, username, password));
    }

    protected SingleSqlConnectionProvider createConnectionProvider(String driverClass, String url, String username, String password) {
        return new DriverSqlConnectionProvider(driverClass, url, username, password).single();
    }

    public SqlPipelineBuilder withAutoCommit(boolean autoCommit) {
        this.autoCommit = autoCommit;
        return self();
    }

    public SqlPipelineBuilder withManualCommit() {
        return withAutoCommit(false);
    }

    public SqlPipelineBuilder withEndOfLineRegex(String regex) {
        this.endOfLineRegex = regex;
        return self();
    }

    public SqlPipelineBuilder withEndOfLineMarker(String marker) {
        return withEndOfLineRegex(Pattern.quote(marker) + "\\s*$");
    }

    /**
     * Store ran script in table
     * @param name Table name
     * @param sequence True if ids are generated by sequence, false if they are generated by auto increment
     */
    public SqlPipelineBuilder withScriptStore(String name, boolean sequence) {
        return withScriptStore(new SqlScriptStore(getConnectionProvider(), name, sequence));
    }

    /**
     * Store ran script in table, don't use sequence to generate ids
     * @param name Table name
     */
    @Override
    public SqlPipelineBuilder withScriptStore(String name) {
        ScriptStore store = ScriptStores.scheme(name);
        if (store == null) {
            return withScriptStore(name, false);
        } else {
            return withScriptStore(scriptStore);
        }
    }

    @Override
    public  Consumer<ScriptStartEvent> createConsumers() {
        Consumer<ScriptEvent> consumer = endConsumer;
        consumer = new SqlLineExecutor(getConnectionProvider(), autoCommit, consumer);
        consumer = notNullNorEmptyFilter(consumer);
        consumer = new MultilineAggregator(endOfLineRegex, MultilineAggregator.LineMarkerStrategy.END, true, consumer);
        consumer = variableReplacer(consumer);
        return scriptReader(consumer);
    }

    protected SqlConnectionProvider getConnectionProvider() {
        return connectionProvider == null ?
            DriverSqlConnectionProvider.create(url, username, password) :
            connectionProvider;
    }

    @Override
    public SqlPipeline build() {
        return new SqlPipeline(getScriptStore(), createScriptScanner(), getConnectionProvider());
    }

}
